# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='type_id',
        ),
    ]
