# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20171009_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
